# Generated by Django 6.0 on 2026-01-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="subtitle",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="budget_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="survey",
            name="completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="survey",
            name="target",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="survey",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("options", models.JSONField(blank=True, null=True)),
                ("required", models.BooleanField(default=True)),
                ("is_ai", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.survey",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["survey", "order"], name="core_sq_svy_order_idx"
                    ),
                    models.Index(
                        fields=["survey", "type"], name="core_sq_svy_type_idx"
                    ),
                ],
            },
        ),
    ]
