# Generated by Codex to align schema with ER diagram (data-preserving).

import datetime

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_date, parse_datetime


def _parse_deadline(value):
    if not value:
        return None
    dt = parse_datetime(value)
    if dt is None:
        date_value = parse_date(value)
        if date_value:
            dt = datetime.datetime.combine(date_value, datetime.time.min)
    if dt and timezone.is_naive(dt):
        dt = timezone.make_aware(dt, timezone=timezone.utc)
    return dt


def _get_tag(tag_cache, Tag, tag_type, name):
    key = (tag_type, name)
    if key in tag_cache:
        return tag_cache[key]
    tag = Tag.objects.filter(name=name, type=tag_type).first()
    if not tag:
        tag = Tag.objects.create(name=name, type=tag_type, created_at=timezone.now())
    tag_cache[key] = tag
    return tag


def migrate_data(apps, schema_editor):
    LegacyAppUser = apps.get_model("core", "LegacyAppUser")
    LegacySurvey = apps.get_model("core", "LegacySurvey")
    LegacySurveyQuestion = apps.get_model("core", "LegacySurveyQuestion")
    LegacyFillRecord = apps.get_model("core", "LegacyFillRecord")
    LegacyPointsLog = apps.get_model("core", "LegacyPointsLog")
    LegacyReport = apps.get_model("core", "LegacyReport")

    AppUser = apps.get_model("core", "AppUser")
    AuthCredential = apps.get_model("core", "AuthCredential")
    AuthToken = apps.get_model("core", "AuthToken")
    Survey = apps.get_model("core", "Survey")
    Questionnaire = apps.get_model("core", "Questionnaire")
    Question = apps.get_model("core", "Question")
    QuestionOption = apps.get_model("core", "QuestionOption")
    Response = apps.get_model("core", "Response")
    PointsLog = apps.get_model("core", "PointsLog")
    Report = apps.get_model("core", "Report")
    Tag = apps.get_model("core", "Tag")
    UserTag = apps.get_model("core", "UserTag")

    user_map = {}
    survey_map = {}
    questionnaire_map = {}
    tag_cache = {}

    for legacy_user in LegacyAppUser.objects.all():
        user = AppUser.objects.create(
            nickname=legacy_user.nickname,
            email=legacy_user.email,
            credit_score=legacy_user.credit_score,
            points=legacy_user.points,
            activity_points=legacy_user.activity_points,
            status="active",
            created_at=legacy_user.created_at,
            updated_at=legacy_user.created_at,
        )
        user_map[legacy_user.id] = user

        AuthCredential.objects.create(
            user=user,
            password_hash=make_password(legacy_user.password),
            created_at=legacy_user.created_at,
            updated_at=legacy_user.created_at,
        )

        if legacy_user.token:
            AuthToken.objects.create(
                user=user,
                token=legacy_user.token,
                expires_at=None,
                created_at=legacy_user.created_at,
            )

        if getattr(legacy_user, "school", None):
            school_tag = _get_tag(tag_cache, Tag, "school", legacy_user.school)
            UserTag.objects.create(
                user=user,
                tag=school_tag,
                created_at=legacy_user.created_at,
            )

        if getattr(legacy_user, "tags", None):
            seen_tags = set()
            for raw_tag in legacy_user.tags.split(","):
                name = raw_tag.strip()
                if not name or name in seen_tags:
                    continue
                seen_tags.add(name)
                interest_tag = _get_tag(tag_cache, Tag, "interest", name)
                UserTag.objects.create(
                    user=user,
                    tag=interest_tag,
                    created_at=legacy_user.created_at,
                )

    for legacy_survey in LegacySurvey.objects.all():
        owner = user_map.get(legacy_survey.owner_id)
        if not owner:
            continue
        survey = Survey.objects.create(
            owner=owner,
            title=legacy_survey.title,
            description=legacy_survey.description,
            estimated_minutes=legacy_survey.estimated_minutes,
            reward_points=legacy_survey.reward_points or 0,
            publish_cost_points=getattr(legacy_survey, "budget_points", 0) or 0,
            deadline=_parse_deadline(getattr(legacy_survey, "deadline", None)),
            status=legacy_survey.status or "draft",
            created_at=legacy_survey.created_at,
            updated_at=getattr(legacy_survey, "updated_at", None) or legacy_survey.created_at,
        )
        survey_map[legacy_survey.id] = survey

        questionnaire = Questionnaire.objects.create(
            survey=survey,
            version=1,
            status=legacy_survey.status or "draft",
            title=legacy_survey.title,
            created_at=legacy_survey.created_at,
            updated_at=getattr(legacy_survey, "updated_at", None) or legacy_survey.created_at,
        )
        survey.active_questionnaire = questionnaire
        survey.save(update_fields=["active_questionnaire"])
        questionnaire_map[legacy_survey.id] = questionnaire

    for legacy_question in LegacySurveyQuestion.objects.all().order_by("order"):
        questionnaire = questionnaire_map.get(legacy_question.survey_id)
        if not questionnaire:
            continue
        question = Question.objects.create(
            questionnaire=questionnaire,
            order_no=legacy_question.order,
            type=legacy_question.type,
            title=legacy_question.title,
            description=None,
            is_required=legacy_question.required,
            config_json=None,
            logic_json=None,
            created_at=legacy_question.created_at,
            updated_at=legacy_question.updated_at,
        )
        options = legacy_question.options or []
        if isinstance(options, list):
            for idx, option in enumerate(options, start=1):
                label = str(option)
                QuestionOption.objects.create(
                    question=question,
                    order_no=idx,
                    label=label,
                    value=label,
                    is_other=False,
                    created_at=legacy_question.created_at,
                )
        else:
            question.config_json = {"options": options}
            question.save(update_fields=["config_json"])

    for legacy_fill in LegacyFillRecord.objects.all():
        survey = survey_map.get(legacy_fill.survey_id)
        user = user_map.get(legacy_fill.user_id)
        if not survey or not user:
            continue
        Response.objects.create(
            survey=survey,
            questionnaire=survey.active_questionnaire,
            user=user,
            status=legacy_fill.status,
            started_at=None,
            submitted_at=legacy_fill.created_at,
            duration_seconds=legacy_fill.duration_seconds,
            risk_flag=False,
            created_at=legacy_fill.created_at,
            updated_at=legacy_fill.created_at,
        )

    for legacy_log in LegacyPointsLog.objects.all():
        user = user_map.get(legacy_log.user_id)
        if not user:
            continue
        points_type = "earn" if legacy_log.delta > 0 else "spend"
        PointsLog.objects.create(
            user=user,
            points_type=points_type,
            delta=legacy_log.delta,
            reason=legacy_log.reason,
            ref_type=None,
            ref_id=None,
            created_at=legacy_log.created_at,
        )

    for legacy_report in LegacyReport.objects.all():
        reporter = user_map.get(legacy_report.reporter_id)
        if not reporter:
            continue
        target_id = None
        detail = None
        if legacy_report.target_type == "survey":
            target = survey_map.get(legacy_report.target_id)
            if target:
                target_id = target.id
            else:
                detail = f"legacy_target_id={legacy_report.target_id}"
        elif legacy_report.target_type == "user":
            target = user_map.get(legacy_report.target_id)
            if target:
                target_id = target.id
            else:
                detail = f"legacy_target_id={legacy_report.target_id}"
        else:
            detail = f"legacy_target_id={legacy_report.target_id}"

        Report.objects.create(
            reporter=reporter,
            target_type=legacy_report.target_type,
            target_id=target_id or 0,
            reason=legacy_report.reason,
            detail=detail,
            status=legacy_report.status or "pending",
            created_at=legacy_report.created_at,
            handled_at=None,
            handled_by=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_survey_question_and_fields"),
    ]

    operations = [
        migrations.RenameModel(old_name="AppUser", new_name="LegacyAppUser"),
        migrations.RenameModel(old_name="Survey", new_name="LegacySurvey"),
        migrations.RenameModel(old_name="FillRecord", new_name="LegacyFillRecord"),
        migrations.RenameModel(old_name="PointsLog", new_name="LegacyPointsLog"),
        migrations.RenameModel(old_name="Report", new_name="LegacyReport"),
        migrations.RenameModel(old_name="SurveyQuestion", new_name="LegacySurveyQuestion"),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("credit_score", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("activity_points", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                ("reward_points", models.IntegerField(default=0)),
                ("publish_cost_points", models.IntegerField(default=0)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.IntegerField(default=1)),
                ("status", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.survey"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="survey",
            name="active_questionnaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_surveys",
                to="core.questionnaire",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_no", models.IntegerField(default=1)),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                ("logic_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.questionnaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_no", models.IntegerField(default=1)),
                ("label", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("is_other", models.BooleanField(default=False)),
                ("extra_config_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("risk_flag", models.BooleanField(default=False)),
                ("evidence_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.questionnaire",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.survey"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.response"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointsLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("points_type", models.CharField(max_length=32)),
                ("delta", models.IntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("ref_type", models.CharField(blank=True, max_length=32, null=True)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.BigIntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_reports",
                        to="core.appuser",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.BigIntegerField()),
                ("action", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("type", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"), name="unique_user_role"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.survey"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "tag"), name="unique_survey_tag"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tag"), name="unique_user_tag"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(name="LegacySurveyQuestion"),
        migrations.DeleteModel(name="LegacyFillRecord"),
        migrations.DeleteModel(name="LegacyPointsLog"),
        migrations.DeleteModel(name="LegacyReport"),
        migrations.DeleteModel(name="LegacySurvey"),
        migrations.DeleteModel(name="LegacyAppUser"),
    ]
