# Generated by Codex to align schema with ER doc constraints/defaults.

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    AppUser = apps.get_model("core", "AppUser")
    Survey = apps.get_model("core", "Survey")
    Questionnaire = apps.get_model("core", "Questionnaire")
    Response = apps.get_model("core", "Response")
    PointsLog = apps.get_model("core", "PointsLog")
    Report = apps.get_model("core", "Report")
    Notification = apps.get_model("core", "Notification")

    AppUser.objects.filter(status__isnull=True).update(status="normal")
    Survey.objects.filter(status="active").update(status="published")
    Survey.objects.filter(status__isnull=True).update(status="draft")
    Questionnaire.objects.filter(status="active").update(status="published")
    Questionnaire.objects.filter(status__isnull=True).update(status="draft")
    Response.objects.filter(status="pending").update(status="submitted")
    Response.objects.filter(status__isnull=True).update(status="in_progress")
    PointsLog.objects.filter(points_type="earn").update(points_type="reward")
    PointsLog.objects.filter(points_type="spend").update(points_type="publish_cost")
    Report.objects.filter(status="pending").update(status="open")
    Report.objects.filter(status__isnull=True).update(status="open")
    Notification.objects.filter(status__isnull=True).update(status="unread")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_er_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="status",
            field=models.CharField(default="normal", max_length=32),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(default="draft", max_length=32),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="status",
            field=models.CharField(default="draft", max_length=32),
        ),
        migrations.AlterField(
            model_name="response",
            name="status",
            field=models.CharField(default="in_progress", max_length=32),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(default="open", max_length=32),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(default="unread", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="unique_answer_response_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "order_no"),
                name="unique_questionnaire_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order_no"),
                name="unique_question_option_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("user", "survey"),
                name="unique_response_user_survey",
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["status", "deadline"], name="survey_status_deadline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["survey", "status"], name="response_survey_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["user", "created_at"], name="response_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointslog",
            index=models.Index(
                fields=["user", "created_at"], name="pointslog_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveytag",
            index=models.Index(fields=["tag"], name="survey_tag_tag_idx"),
        ),
        migrations.AddIndex(
            model_name="usertag",
            index=models.Index(fields=["tag"], name="user_tag_tag_idx"),
        ),
        migrations.RunPython(normalize_statuses, reverse_code=migrations.RunPython.noop),
    ]
