# Generated by Codex on 2026-01-27.

from django.db import migrations, models
from django.db.models import Count


def backfill_survey_completed(apps, schema_editor):
    Survey = apps.get_model("core", "Survey")
    Response = apps.get_model("core", "Response")

    counts = (
        Response.objects.filter(submitted_at__isnull=False)
        .values("survey_id")
        .annotate(cnt=Count("id"))
    )
    count_map = {row["survey_id"]: row["cnt"] for row in counts}
    for survey in Survey.objects.all():
        survey.completed = count_map.get(survey.id, 0)
        survey.save(update_fields=["completed"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_answer_id_alter_appuser_id_alter_auditlog_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="difficulty",
            field=models.IntegerField(default=3),
        ),
        migrations.RunPython(backfill_survey_completed, migrations.RunPython.noop),
    ]
