# Generated by Django 6.0 on 2026-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_survey_task_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="survey",
            name="target",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("survey_type", "Survey Type"),
                    ("interest", "Interest"),
                    ("school", "School"),
                ],
                max_length=32,
            ),
        ),
    ]
