# Generated by Django 6.0 on 2026-02-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_survey_completed_survey_target_alter_tag_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_type", models.CharField(max_length=32)),
                ("ref_id", models.CharField(db_index=True, max_length=128)),
                ("vector", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ref_type", "ref_id"], name="idvector_ref_idx"
                    ),
                    models.Index(
                        fields=["ref_type", "created_at"],
                        name="idvector_type_created_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyUserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cosine", models.FloatField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.survey"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["cosine"], name="survey_user_cosine_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "user"), name="unique_survey_user_similarity"
                    )
                ],
            },
        ),
    ]
