# Generated by Django 6.0 on 2026-02-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_idvector_surveyusersimilarity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTagWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tag"], name="user_tagweight_tag_idx"),
                    models.Index(fields=["user"], name="user_tagweight_user_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tag"), name="unique_user_tag_weight"
                    )
                ],
            },
        ),
    ]
