# Generated by Django 6.0 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usertagweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("survey_type", "Survey Type"),
                    ("interest", "Interest"),
                    ("school", "School"),
                    ("gender", "Gender"),
                    ("age", "Age"),
                    ("grade", "Grade"),
                    ("college", "College"),
                    ("major", "Major"),
                    ("mbti", "MBTI"),
                    ("organization", "Organization"),
                    ("consumption", "Consumption"),
                    ("career", "Career"),
                    ("skill", "Skill"),
                    ("status", "Status"),
                ],
                max_length=32,
            ),
        ),
    ]
