# Generated by Django 6.0 on 2026-03-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_tag_type_profile_choices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="passwordresetcode",
            name="reset_code_lookup_idx",
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="code_hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="purpose",
            field=models.CharField(
                choices=[("register", "注册验证"), ("reset", "密码重置")],
                default="reset",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(
                fields=["email", "purpose", "is_used", "expires_at"],
                name="email_code_lookup_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="passwordresetcode",
            name="code",
        ),
    ]
