# Generated by Django 6.0 on 2026-03-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_email_verification_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(db_index=True, default="unread", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("system", "系统消息"),
                            ("team_invite", "队伍邀请"),
                            ("points_gift", "积分赠送"),
                        ],
                        default="system",
                        max_length=32,
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("points_amount", models.IntegerField(default=0)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="core.appuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("max_members", models.IntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("closed", "已关闭")],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to="core.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=1)),
                ("last_invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to="core.appuser",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to="core.appuser",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "邀请中"),
                            ("joined", "已加入"),
                            ("left", "已离开"),
                            ("kicked", "被移除"),
                        ],
                        default="joined",
                        max_length=32,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="core.appuser",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="msg_user_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "-created_at"], name="msg_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="msg_ref_type_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["owner", "status"], name="team_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["status", "-created_at"], name="team_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(fields=["team", "status"], name="tinv_team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["invitee", "status"], name="tinv_invitee_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["inviter", "invitee"], name="tinv_inviter_invitee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teaminvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("team", "invitee"),
                name="unique_team_invitee_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["team", "status"], name="tm_team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["user", "status"], name="tm_user_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_team_member"
            ),
        ),
    ]
