# Generated by Django 6.0 on 2026-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_message_team_teaminvitation_teammember_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[("member", "普通成员"), ("admin", "管理员")],
                default="member",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["team", "role"], name="tm_team_role_idx"),
        ),
    ]
