# Generated by Django 4.2.16 on 2026-04-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('short_duration', '短时长回答'), ('suspicious_behavior', '可疑行为'), ('abnormal_survey', '异常问卷'), ('multiple_submissions', '多次提交'), ('ip_anomaly', 'IP异常')], max_length=32)),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=32)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='risk_event_user_idx'), models.Index(fields=['survey'], name='risk_event_survey_idx'), models.Index(fields=['event_type'], name='risk_event_type_idx'), models.Index(fields=['severity'], name='risk_event_severity_idx'), models.Index(fields=['created_at'], name='risk_event_created_idx')],
            },
        ),
    ]
