# Generated by Django 6.0 on 2026-04-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_appuser_level_title'),
        ('core', '0017_alter_auditlog_operator'),
    ]

    operations = [
    ]
