# Generated by Django 4.2.16 on 2026-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_recommendationclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
