# Generated by Django 6.0 on 2026-05-02 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appuser_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('claimed', '已点击'), ('completed', '已完成'), ('abandoned', '超时未完成')], default='claimed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=64, unique=True)),
                ('rule_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('event_type', models.CharField(choices=[('short_duration', '短时长回答'), ('ip_anomaly', 'IP异常'), ('device_anomaly', '设备异常'), ('time_anomaly', '时间异常'), ('fixed_answer', '固定答案检测')], max_length=32)),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=32)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='teaminvitation',
            name='unique_team_invitee_pending',
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='clicked_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='deleted_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='refresh_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbehaviorlog',
            name='event_type',
            field=models.CharField(choices=[('impression', '曝光'), ('click', '点击'), ('refresh', '刷新一次'), ('dismiss', '不感兴趣')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userbehaviorlog',
            name='scene',
            field=models.CharField(choices=[('task_list', '任务列表'), ('task_refresh', '任务刷新一次'), ('home_feed', '首页Feed'), ('home_trending', '首页Trending'), ('fill_entry', '填写入口')], default='task_list', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(fields=('team', 'invitee'), name='unique_team_invitee_pending'),
        ),
        migrations.AddField(
            model_name='recommendationclaim',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dailyrecommendation'),
        ),
        migrations.AddField(
            model_name='recommendationclaim',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_claims', to='core.survey'),
        ),
        migrations.AddField(
            model_name='recommendationclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['rule_code'], name='risk_rule_code_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['enabled'], name='risk_rule_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['priority'], name='risk_rule_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationclaim',
            index=models.Index(fields=['user', 'status'], name='rc_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationclaim',
            index=models.Index(fields=['status'], name='rc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationclaim',
            index=models.Index(fields=['claimed_at'], name='rc_claimed_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationclaim',
            constraint=models.UniqueConstraint(fields=('user', 'survey', 'claimed_at'), name='unique_user_survey_claim'),
        ),
    ]
