# Generated by Django 4.2.16 on 2026-05-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appuser_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=64, unique=True)),
                ('rule_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('event_type', models.CharField(choices=[('short_duration', '短时长回答'), ('ip_anomaly', 'IP异常'), ('device_anomaly', '设备异常'), ('time_anomaly', '时间异常'), ('fixed_answer', '固定答案检测')], max_length=32)),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=32)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '风控规则',
                'verbose_name_plural': '风控规则',
                'ordering': ['priority', '-created_at'],
                'indexes': [
                    models.Index(fields=['rule_code'], name='risk_rule_code_idx'),
                    models.Index(fields=['enabled'], name='risk_rule_enabled_idx'),
                    models.Index(fields=['priority'], name='risk_rule_priority_idx'),
                ],
            },
        ),
    ]