# Generated by Django 6.0 on 2026-04-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_homemoduleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', '曝光'), ('click', '点击'), ('refresh', '换一批'), ('dismiss', '不感兴趣')], max_length=32)),
                ('scene', models.CharField(choices=[('task_list', '任务列表'), ('task_refresh', '任务换一批'), ('daily_recommend', '每日推荐'), ('home_feed', '首页Feed'), ('home_trending', '首页Trending'), ('fill_entry', '填写入口')], default='task_list', max_length=32)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='ubl_event_created_idx'), models.Index(fields=['scene', 'created_at'], name='ubl_scene_created_idx'), models.Index(fields=['user', 'created_at'], name='ubl_user_created_idx'), models.Index(fields=['survey', 'created_at'], name='ubl_survey_created_idx')],
            },
        ),
    ]
