from django.urls import path

from .controller.admin_controller import (
    admin_login,
    analytics_ai,
    analytics_recommend,
    announcement_list,
    approve_survey,
    batch_adjust_points,
    batch_update_user_status,
    create_announcement,
    create_survey,
    dashboard_stats,
    dashboard_trend,
    delete_survey,
    delete_user,
    export_dashboard,
    export_surveys,
    export_users,
    force_close_survey,
    notification_list,
    notification_mark_all_read,
    notification_mark_read,
    operation_logs,
    pending_surveys,
    reject_survey,
    risk_control,
    survey_detail,
    survey_list,
    update_survey,
    update_user_info,
    update_user_status,
    user_detail,
    user_list,
)

urlpatterns = [
    path("login", admin_login, name="admin_login"),
    path("dashboard/stats", dashboard_stats, name="admin_dashboard_stats"),
    path("dashboard/trend", dashboard_trend, name="admin_dashboard_trend"),
    path("dashboard/export", export_dashboard, name="admin_dashboard_export"),
    path("users", user_list, name="admin_user_list"),
    path("users/<int:user_id>", user_detail, name="admin_user_detail"),
    path("users/<int:user_id>/info", update_user_info, name="admin_update_user_info"),
    path("users/<int:user_id>/delete", delete_user, name="admin_delete_user"),
    path("users/<int:user_id>/status", update_user_status, name="admin_update_user_status"),
    path("users/batch/status", batch_update_user_status, name="admin_batch_update_user_status"),
    path("users/batch/points", batch_adjust_points, name="admin_batch_adjust_points"),
    path("users/export", export_users, name="admin_export_users"),
    path("surveys", survey_list, name="admin_survey_list"),
    path("surveys/pending", pending_surveys, name="admin_pending_surveys"),
    path("surveys/create", create_survey, name="admin_create_survey"),
    path("surveys/<int:survey_id>", survey_detail, name="admin_survey_detail"),
    path("surveys/<int:survey_id>/update", update_survey, name="admin_update_survey"),
    path("surveys/<int:survey_id>/delete", delete_survey, name="admin_delete_survey"),
    path("surveys/<int:survey_id>/close", force_close_survey, name="admin_force_close_survey"),
    path("surveys/<int:survey_id>/approve", approve_survey, name="admin_approve_survey"),
    path("surveys/<int:survey_id>/reject", reject_survey, name="admin_reject_survey"),
    path("surveys/export", export_surveys, name="admin_export_surveys"),
    path("analytics/recommend", analytics_recommend, name="admin_analytics_recommend"),
    path("analytics/ai", analytics_ai, name="admin_analytics_ai"),
    path("risk", risk_control, name="admin_risk_control"),
    path("announcements", announcement_list, name="admin_announcement_list"),
    path("announcements/create", create_announcement, name="admin_create_announcement"),
    path("operation_logs", operation_logs, name="admin_operation_logs"),
    path("notifications", notification_list, name="admin_notification_list"),
    path("notifications/<int:message_id>/read", notification_mark_read, name="admin_notification_mark_read"),
    path("notifications/mark-all-read", notification_mark_all_read, name="admin_notification_mark_all_read"),
]
