version: "1.0"
name: pipeline-20260207
displayName: pipeline-20260207
triggers:
  trigger: auto
  schedule:
    - cron: "* * 8 * * ? *"
stages:
  - name: stage-532932c6
    displayName: 更新部署服务器
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: test
          hostID:
            - 4ffe73d7-481f-406d-969a-c052ac1380d5
        scriptType: SH
        script:
          - "# 调用改造后的统一安全部署脚本"
          - bash /home/six_element/home/six_element_app/The-Sixth-ELement/deploy/update_deploy.sh
        gitClone: false
        notify: []
        strategy:
          retry: "0"
